//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatisticsTasks.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormTable
    {
        public int Id { get; set; }
        public string CodeTask { get; set; }
        public string TaskName { get; set; }
        public string Formula { get; set; }
    }
}
